spring:
  application:
    name: eureka-client # что бы на UI http://localhost:8761/ отображалось Application имя
eureka:
  client:
    healthcheck:
      enabled: true
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    eureka-service-url-poll-interval-seconds: 35 # 3 укажите интервал в 35 сек через который клиент шлет эхо запрос на сервер
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
